
Создание тестовой базы:
  stage: build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - changes:
      - features/**/*
      - fixtures/**/*
      - src/**/*
      - tests/**/*
  tags:
    - OneS
  script:
    - vci run close-all-1c-process
    - vci run create-base
    - vci run launch-IB-update

Компиляция внешних файлов:
  stage: build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - changes:
      - src/**/*
  tags:
    - OneS
  script:
    - vci run close-all-1c-process
    - vci run compilecf
    - vci run compilecfe
    - vci run compileepf
